### ISSUE TITLE
Different import behavior in bundle

### ISSUE THREAD

**Issue by adelespinasse** [systemjs/babel-plugin-transform-cjs-system-wrapper#12] opened 2017-04-13 18:20 UTC
I think this is the right repo for this bug, but I still don't understand how all the pieces of this stack fit together, so please feel free to move if this is the wrong place. Or it's possible that this isn't a bug at all, and I'm doing something wrong.

I'm trying to upgrade to 0.17.0-beta.41 of jspm (currently on 0.17.0-beta.32). I had the following import statement:
```
import getMuiTheme from 'material-ui/styles/getMuiTheme';
```
[material-ui](https://github.com/callemall/material-ui) seems to be CJS, compiled with Babel 6.x from ES6. This particular module exports getMuiTheme (a function) with:
```
exports.default = getMuiTheme;
```
Before, when I imported this, my imported getMuiTheme was a function. This still works in beta.41 when I run in debug mode (everything transpiled in the browser).

When I build a complete bundle with `jspm build`, though, my imported getMuiTheme is an object, with property "default" which is the function. I suspect this may actually be considered "correct" behavior, but I would think it should work the same way in a bundle and in a development set up, shouldn't it?

(The former behavior would be more convenient for my existing code, of course.)

I've made a small-ish repo [here](https://github.com/adelespinasse/jspmbuildbug) that demonstrates the issue. Loading index.html runs it in normal development mode. To run the bundled version, run `jspm build main.js` and load index-build.html.

I tried to make a demo using my own minimal CJS module, but the behavior seems different, so this uses material-ui.

**Comment by adelespinasse** [comment] 2017-05-19 15:39
I've updated [this repo](https://github.com/adelespinasse/jspmbuildbug) to be a more minimal reproduction of the issue. It no longer depends on material-ui.

I understand the bug a bit better now. Certain packages that are compiled from ES6 by Babel have an idiom like this in their generated cjs code:

```
Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = defaultFunc;
```

This seems to be generated when the original ES6 source looks like:

```
export default function defaultFunc();
```

I don't know if this should really be considered "correct" transpilation, but it's out there in many packages. An example is [getMuiTheme in Material-UI](https://github.com/callemall/material-ui/blob/master/src/styles/getMuiTheme.js).

When importing something that was exported with `export default`, we expect to be able to do:

```
import defaultFunc from 'defaultFunc';
```

and in these cases it works as expected during development. But if you build it with `jspm build`, then the value of defaultFunc in the importing module is not the value that was exported with `export default`; instead it's an Object with a property called `default` which is the exported value.

One workaround would be to do this in the calling module:

```
import defaultFunc from 'defaultFunc';
defaultFunc = (defaultFunc.default || defaultFunc);
```

but that clearly isn't something we want to have to write.

The output in the bundle looks something like this:

```
$__System.registerDynamic('b', [], true, function ($__require, exports, module) {
  'use strict';

  var global = this || self,
      GLOBAL = global;
  Object.defineProperty(exports, "__esModule", {
    value: true
  });

  exports.default = defaultFunc;

  function defaultFunc() {
    console.log('defaultFunc called');
  }
});
```

All of this is illustrated in the repo I linked to above. Instead of cross-compiling the imported module from ES6 to cjs, I just wrote a cjs module with the `Object.defineProperty` idiom in it, but it works the same. And for some reason I called the module `mod` instead of `defaultFunc`.

**Comment by adelespinasse** [comment] 2017-05-19 15:45
Note: I filed the issue in this repo because, when I filed [this issue](https://github.com/systemjs/systemjs/issues/1490) in SystemJS, @guybedford moved it to #9 in this repo. It seemed like a similar type of problem. Feel free to move if appropriate.

It's very frustrating; this has been keeping me from upgrading beyond 0.17.0-beta.32 of jspm for quite a while, but more recent versions fix other problems that I've been having.

**Comment by guybedford** [comment] 2017-05-20 14:56
This isn't supposed to work in the latest SystemJS I believe. We did originally do this interop as you'd expect, but the problem is that there are cases where modules do this, but then still have a non-standard edge case described in the release notes at https://github.com/ModuleLoader/es-module-loader/releases/tag/2.1.4.

Basically, tools should just be treating these "default only" modules as "module.exports = ..." in the transpilation process.

As a result, the recommended way to deal with these modules is via:

```js
import getMuiTheme from 'material-ui/styles/getMuiTheme';
getMuiTheme.default
```

The development mode being out of sync with the build process sounds like it is a result of jspm not yet being upgraded to SystemJS 0.20.11. I'll aim to make this upgrade soon, so the two will be in sync again.

**Comment by jrauschenbusch** [comment] 2017-05-28 11:43
@guybedford I think this should be fixed with https://github.com/ModuleLoader/es-module-loader/releases/tag/2.2.0. Once SystemJS has been updated to this version and JSPM is upgraded to the updated SystemJS version, this ticket should be closed.

**Comment by guybedford** [comment] 2017-05-29 15:43
Unfortunately I think this exact issue is a duplicate of https://github.com/systemjs/builder/issues/775, which is still a pending todo.

**Comment by guybedford** [comment] 2017-05-30 06:51
The fix in https://github.com/systemjs/builder/issues/775 should finally make this work.

**Closed as completed** 2017-05-30 06:52 UTC
